version: '3'

services:
  frontend:
    image: amieldelatorre/weighttracker-frontend:latest
    container_name: frontend
    restart: unless-stopped
    volumes:
      - ./config.js:/usr/share/nginx/html/scripts/config.js:ro
    ports: 
      - 8080:80
    networks:
      - network-backend
    depends_on:
      - backend
    environment:
      - TZ=Pacific/Auckland

  backend:
    image: amieldelatorre/weighttracker-backend:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - 7070:8080
    networks:
      - network-db
      - network-backend
    environment:
      - TZ=Pacific/Auckland
      - WeightTracker_ConnectionStrings__WebAPIDatabaseConnection=Host=${POSTGRES_HOST:-pg-db}; Port=${POSTGRES_PORT:-5432}; Database=${POSTGRES_DB:-weighttracker}; Username=${POSTGRES_USER:-root}; Password=${POSTGRES_PASSWORD:-root}
      - MIGRATE_DATABASE=True
    depends_on:
      - pg-db
  
  pg-db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    networks:
      - network-db
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-weighttracker}
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      TZ: Pacific/Auckland

networks:
  network-backend:
    external: false
  network-db:
    external: false    
     