version: '3'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports: 
      - 8080:80
    networks:
      - network-backend
    depends_on:
      - backend
    environment:
      - TZ=Pacific/Auckland

  backend:
    build: ./backend/WeightTracker
    container_name: backend
    restart: unless-stopped
    ports:
      - 7070:8080
    networks:
      - network-db
      - network-backend
    environment:
      - WeightTracker_ConnectionStrings__WebAPIDatabaseConnection=Host=${POSTGRES_HOST:-pg-db}; Port=${POSTGRES_PORT:-5432}; Database=${POSTGRES_DB:-weighttracker}; Username=${POSTGRES_USER:-root}; Password=${POSTGRES_PASSWORD:-root}
      - MIGRATE_DATABASE=True
      - TZ=Pacific/Auckland
    depends_on:
      - pg-db
  
  pg-db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    networks:
      - network-db
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: weighttracker
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: Pacific/Auckland

networks:
  network-backend:
    external: false
  network-db:
    external: false    
     