name: Build and Test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  #pull_request:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.0.x' ]
    env:
      working-directory: ./backend/WeightTracker
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Run tests for backend
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore
        working-directory: ${{ env.working-directory }}

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{ env.working-directory }}

      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: ${{ env.working-directory }}
      
      # Test building of docker image
      - name: Set up Docker QEMU Emulation
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Docker Build Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          platforms: linux/amd64,linux/arm64
          push: false

      - name: Docker Build Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend/WeightTracker
          platforms: linux/amd64,linux/arm64
          push: false